const actionsTypes = {
	RESET: "RESET",
	BACKSPACE: "BACKSPACE",
	SET_ACCUMULATOR: "SET_ACCUMULATOR",
	SET_TOTAL: "SET_TOTAL",
	SET_CURRENT_NUMBER: "SET_CURRENT_NUMBER",
	SET_CURRENT_OPERATION: "SET_CURRENT_OPERATION",
	UPDATE_EXPRESSION: "UPDATE_EXPRESSION",
};

export default actionsTypes;
